stack: binTree.o Main.o Node.o Tree.o
		g++ -g -o binTree binTree.o Main.o Node.o Tree.o

binTree.o:
		g++ -g -c binTree.cpp

Main.o:
		g++ -g -c Main.cpp

Node.o:
		g++ -g -c Node.cpp

Tree.o:
		g++ -g -c Tree.cpp

clean:
		rm binTree *.o

