##
## Auto Generated makefile by VimLite
## Do not edit this file, any manual changes will be erased
##

##
## User defined environment variables
##
CodeLiteDir:=/usr/share/codelite
VimLiteDir:=~/.vimlite

## Debug
ProjectName            :=Pessoa
ConfigurationName      :=Debug
IntermediateDirectory  :=$(ConfigurationName)
OutDir                 := $(IntermediateDirectory)
WorkspacePath          :="/Users/rodrigo/Projetos/mestrado/fase1/pa/trabalhos"
ProjectPath            :="/Users/rodrigo/Projetos/mestrado/fase1/pa/trabalhos/Pessoa"
CurrentFileName        :=
CurrentFilePath        :=
CurrentFileFullPath    :=
User                   :=rodrigo
Date                   :=2012-03-15
CodeLitePath           :="/Users/rodrigo/.codelite"
LinkerName             :=g++
ArchiveTool            :=ar rcus
SharedObjectLinkerName :=g++ -shared -fPIC
ObjectSuffix           :=.o
DependSuffix           :=.o.d
PreprocessSuffix       :=.o.i
DebugSwitch            :=-gstab
IncludeSwitch          :=-I
LibrarySwitch          :=-l
OutputSwitch           :=-o 
LibraryPathSwitch      :=-L
PreprocessorSwitch     :=-D
SourceSwitch           :=-c 
CompilerName           :=g++
C_CompilerName         :=gcc
OutputFile             :=$(IntermediateDirectory)/$(ProjectName)
Preprocessors          :=
ObjectSwitch           :=-o 
ArchiveOutputSwitch    := 
PreprocessOnlySwitch   :=-E 
ObjectsFileList        :="/Users/rodrigo/Projetos/mestrado/fase1/pa/trabalhos/Pessoa/Pessoa.txt"
MakeDirCommand         :=mkdir -p
CmpOptions             := -g -Wall $(Preprocessors)
C_CmpOptions           := -g Wall $(Preprocessors)
LinkOptions            :=  
IncludePath            :=  $(IncludeSwitch). $(IncludeSwitch). 
RcIncludePath          :=
Libs                   :=
LibPath                := $(LibraryPathSwitch). 


Objects=\
	$(IntermediateDirectory)/main$(ObjectSuffix) 

##
## Main Build Targets
##
all: PostBuild

$(OutputFile): MakeDirStep PreBuild $(Objects)
	@$(MakeDirCommand) "$(@D)"
	$(LinkerName) $(OutputSwitch)$(OutputFile) $(Objects) $(LibPath) $(Libs) $(LinkOptions)

MakeDirStep:
	@test -d "$(ConfigurationName)" || $(MakeDirCommand) "$(ConfigurationName)"

PreBuild:

PostBuild: $(OutputFile)


##
## Objects
##
$(IntermediateDirectory)/main$(ObjectSuffix): main.cpp $(IntermediateDirectory)/main$(DependSuffix)
	$(CompilerName) $(SourceSwitch) "/Users/rodrigo/Projetos/mestrado/fase1/pa/trabalhos/Pessoa/main.cpp" $(CmpOptions) $(ObjectSwitch)$(IntermediateDirectory)/main$(ObjectSuffix) $(IncludePath)
$(IntermediateDirectory)/main$(DependSuffix): main.cpp
	@$(CompilerName) $(CmpOptions) $(IncludePath) -MG -MP -MT$(IntermediateDirectory)/main$(ObjectSuffix) -MF$(IntermediateDirectory)/main$(DependSuffix) -MM "/Users/rodrigo/Projetos/mestrado/fase1/pa/trabalhos/Pessoa/main.cpp"

$(IntermediateDirectory)/main$(PreprocessSuffix): main.cpp
	@$(CompilerName) $(CmpOptions) $(IncludePath) $(PreprocessOnlySwitch) $(OutputSwitch) $(IntermediateDirectory)/main$(PreprocessSuffix) "/Users/rodrigo/Projetos/mestrado/fase1/pa/trabalhos/Pessoa/main.cpp"


-include $(IntermediateDirectory)/*$(DependSuffix)
##
## Clean
##
clean:
	$(RM) $(IntermediateDirectory)/main$(ObjectSuffix)
	$(RM) $(IntermediateDirectory)/main$(DependSuffix)
	$(RM) $(IntermediateDirectory)/main$(PreprocessSuffix)
	$(RM) $(OutputFile)


